version: '3'
services:
  wordpress:
    container_name: wordpress
    image: wp-img
    build:
      context: src/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    networks:
      - network01
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: always
  nginx:
    container_name: nginx
    image: nginx-img
    build:
      context: src/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - network01
    volumes:
      - wordpress:/var/www/html
    restart: always
  mariadb:
    container_name: mariadb
    image: mariadb-img
    build:
      context: src/mariadb
      dockerfile: Dockerfile
    networks:
      - network01
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  /home/ksaelim/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ksaelim/data/mariadb

networks:
  network01:
    name: inception-network
    driver: bridge
